### ISSUE TITLE
Download logo not found which causes browser rendering issues, especially on Chrome

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe.github.io#111]
@Joe-Winchester commented on [Wed Dec 16 2020](https://github.com/zowe/community/issues/909)

**Describe the bug**
https://zowe.jfrog.io/zowe/list/libs-release-local/org/zowe/download/legal.html?version=1.17.0
There is a missing graphic reference where the page is trying to load https://raw.githubusercontent.com/openmainframeproject/artwork/master/projects/zowe/zowe-white.svg.  

This has moved to https://github.com/openmainframeproject/artwork/blob/master/projects/zowe/icon/white/zowe-icon-white.svg.  

**Expected behavior**
The graphic should be there

**Screenshots**
![image](https://user-images.githubusercontent.com/28100302/102374890-c31eb000-3fb9-11eb-9cb1-f57a512c37eb.png)

**Comment by nannanli** [comment]
In Firefox, the header now looks like this. The source for the download page is not maintained in this repo as I could not find the referenced image. 
<img width="815" alt="image" src="https://user-images.githubusercontent.com/14340789/102439353-1ac02880-4059-11eb-8051-d089bc82fbfc.png">

@jmertic  **Hi John,** could you help on this issue? Or is there a way other community members or myself could access the source file to fix it? Many thanks!

**Comment by jmertic** [comment]
Fixed now. For reference, the download flow is maintained in Artifactory at https://zowe.jfrog.io/ui/repos/tree/General/libs-release-local%2Forg%2Fzowe%2Fdownload
