### ISSUE TITLE
Complete remaining work for zowe.org redesign

### ISSUE THREAD

**Issue by nannanli** [zowe/zowe.github.io#125]
This issue tracks all the issues and activities that must be complete before we roll out the redesigned Zowe website. 

###  1. Design Updates
- [x] Update the links to doc site 
- [x] Update and test other links (meetings, Zowe resources, supporting resources) 
        - For each case study in the component introduction section, they should link to the Medium site. Can be a specific blog about the corresponding component. 
- [x] Update the Zowe introduction video link to point to the new one and upload both the deck used for the video as well as the script 
- [x] Update the Zowe description to be the latest (includes Zowe mobile and Zowe SDKs)
- [x] Upload the icons for the metrics section @IlyaKreynin will send the Carbon icons. 
- [x] Test and fix the Metrics number display. The numbers here will be dynamically fetched from an API but the API's gave some errors when they were used in production.  @IlyaKreynin will send the updated links. 
- [x] Blog section should have some text 
- [x] The first page needs reorg. @IlyaKreynin will send the new design. 
- [x] New visual design for the Learn page. @IlyaKreynin will send the new design. 
- [x] Community page: Add a Recurring meetings section such as zlc, tsc, etc. 
- [x] Unify the heading style on different pages 

### 2. Community Review and Feedback 

- [x] Send out the preview site to the community for review and address feedback. 

### 3. Promotion
- [ ] Write and publish a blog on Medium to talk about the new design and experience.

**Comment by covalentbond** [comment]
- [ ] Images in the `How Mainframers use Zowe` Section needs to be updated with better quality one's which can be found [here](https://deploy-preview-121--condescending-dubinsky-4645a9.netlify.app/)

![image](https://user-images.githubusercontent.com/53327173/110302465-47178f80-801f-11eb-918d-e3f4efe832b3.png)
