### ISSUE TITLE
Make Zowe Community Stats visible on homepage

### ISSUE THREAD

**Issue by Tbr00ksy** [zowe/zowe.github.io#16]
Can we make live stat's available on homepage from our GitHub analytics (Open in private window): http://jayne.zowe.org:5601/

Stats to display: 
'# of downloads (from giza server)
'# of contributors
'# of commits
'# of Zowe Conformant Apps

see CNCF for inspiration: https://www.cncf.io/

**Comment by jmertic** [comment]
Good idea - but let's look at a future version for this. Will also help when we have a backend for managing this automatically.

**Comment by pwassel** [comment]
@jmertic where did we end up w/ this request?  i am looking for stats across the zowe project - similar to stackalytics for openstack - i.e. https://www.stackalytics.com/

**Comment by jmertic** [comment]
We have a ton of stats available at https://insights.lfx.linuxfoundation.org/projects/open-mainframe-project%2Fzowe/dashboard - let me know what the group would like displayed and we can see how to best do it.

**Comment by pwassel** [comment]
Ah - beauty!  Didn't know this existed.  Thx.
