### ISSUE TITLE
Add the core infrastructure initiative badge to homepage

### ISSUE THREAD

**Issue by Tbr00ksy** [zowe/zowe.github.io#17]
![Screen Shot 2019-08-14 at 9 46 24 AM](https://user-images.githubusercontent.com/36775778/63026012-661c6280-be78-11e9-91ec-4718591b1aed.png)

https://bestpractices.coreinfrastructure.org/en/projects/2226

**Comment by jmertic** [comment]
Addressed in https://github.com/zowe/zowe.github.io/pull/23
