### ISSUE TITLE
Add Zowe Workflow wiZard to the Zowe landing page

### ISSUE THREAD

**Issue by pdubz3** [zowe/zowe.github.io#214]
Now that the Workflow wiZard has been contributed (and successfully built) we should add it to the landing page as an official incubator project similar to Zowe Mobile.  

Here's the text that I suggest we use:

**Zowe Workflow wiZard (Incubator)**

The Workflow wiZard delivers a workflow builder which simplifies the creation of z/OSMF workflows.  These workflows can be very helpful for automating workloads or guiding users through a set of ordered steps to complete a task, but they can also be complex and challenging to create. The workflow builder was created to address these challenges.

Code on GitHub |  Connect on Slack |  Learn more

![image](https://user-images.githubusercontent.com/38769324/130273980-d711e245-d29b-4cd6-8c1f-a429c1e69ec1.png)

This can also be found in the attached word document, complete with a recommended image and with all of the correct links also included.  

[Zowe Workflow wiZard.docx](https://github.com/zowe/zowe.github.io/files/7023292/Zowe.Workflow.wiZard.docx)

**Comment by pdubz3** [comment]
We also need to add a new link to this new section above where we index all of the sections:

Zowe is composed of several components, each improving the learning ability, accessibility, and possibility of mainframe development.

 Zowe Application Framework
 Zowe API Mediation Layer
 Zowe CLI
 Zowe Explorer
 Zowe Client SDKs - under development
 Zowe Mobile - Incubator
 ZEBRA (Zowe Embedded Browser for RMF/SMF and APIs) - Incubator

**Comment by balhar-jakub** [comment]
The URL to verify is here: https://deploy-preview-216--condescending-dubinsky-4645a9.netlify.app

**Comment by nannanli** [comment]
The changes are live on zowe.org now.
