### ISSUE TITLE
Organize the components list per status 

### ISSUE THREAD

**Issue by nannanli** [zowe/zowe.github.io#217]
On zowe.org, in the introduction section, there is a list of components with links for a deeper-dive. Some of these components are indicated with status labels such as under development or incubation. The active components get a list of conformance plug-ins but that's not shown on the landing page. So the suggestion here is: 

- Organize the component list per status (Active, Under Development, Incubator) 
- For component sections, add links to the conformant apps page. For example for APIML, add a new link saying "View Conformant Apps"

**Comment by balhar-jakub** [comment]
I am closing this issue as we reflected this via the tags on all of the projects.
