### ISSUE TITLE
Out-of-date information

### ISSUE THREAD

**Issue by nannanli** [zowe/zowe.github.io#282]
- [x] The **Master the Mainframe** should be updated to **IBM Z Xplore** on the Learn page. 
- [x] On the Extend page, extending Zowe Explorer should be added as one of the ways. 
- [x] On the Download page, the doc links in the Previous releases need to be fixed.

**Comment by samanthasusu** [comment]
- The **Zowe auxiliary service** should direct to the Zowe auxiliary service section on the Installing and configuring the Zowe cross memory server page.

- On the Configuring z/OSMF page, the link [(https://mvs.ibm.com:443/zosmf/restjobs/jobs)](url) for the example is invalid. It should be updated. 

- On the Configuring z/OSMF Lite page: 
   1. The link for **Configuring z/OSMF Lite (for non-production use)** is invalid. 
   2. The Sample jobs package page displays with "Page not Found". 
   3. The link for **z/OSMF Configuration Guide** is invalid (content not found). 
   4. The link for **Running job IZUMKFS to create the z/OSMF user file system** is invalid. 
   5. The links for **Enabling the z/OSMF data set and file REST services** and **Enabling the z/OSMF Workflow REST services and Workflows task UI** are valid but no actions performed after click. 
   6. The link for **Appendix C. Adding more users to z/OSMF** is invalid.
   7. The link for **z/OSMF Configuration Guide** in the Appendix C. Adding more users to z/OSMF section is invalid with "content not found".

**Comment by samanthasusu** [comment]
- On the Installing Zowe runtime from a convenience build page, 
1. The link for the post-download page for Version 1.4.0 is invalid. 
2. The link for z/OSMF Workflows Tutorial is invalid.

**Comment by samanthasusu** [comment]
- On the [Using Zowe SDKs page](https://docs.zowe.org/stable/user-guide/sdks-using), the link for **npm semver** is invalid. 
- On the [Onboarding a REST API service with the Plain Java Enabler ](https://docs.zowe.org/stable/extend/extend-apiml/onboard-plain-java-enabler), the links for **Zowe API ML TLS requirements** and **SAF keyring** are invalid. 
- On the [Onboarding a service with the Zowe API Meditation Layer without an onboarding enabler ](https://docs.zowe.org/stable/extend/extend-apiml/onboard-direct-eureka-call)page, the relative links for from **registering with the discovery service** to **external resources** don't work. The same as **Catalog parameters, Service parameters, Routing parameters, Authentication parameters, and API Info parameters**. 
On the same page, the links for Installing the **Zowe runtime on z/OS**, **custom metadata.md**, and **Enabling PassTicket creation for API Services that Accept PassTickets** are invalid. 
- On the [Onboarding a Spring Boot based REST API Service](https://docs.zowe.org/stable/extend/extend-apiml/onboard-spring-boot-enabler) page, the links for all subtitles under **3. Configuring your Spring Boot based service to onboard with API ML** are invalid. The same to **Unregistering your service with API ML** and **Basic routing**.
