### ISSUE TITLE
404 Error Page

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe.github.io#41]
@jmertic

Currently if we access old links, for example, https://zowe.org/download/, it will show a standard Github Pages error page. It has link to Github Pages documentation. There is no guidance what action the end-user should take for perspective of Zowe user.

Suggestion:

Create customized 404 pages guide the user to the new website. We can do some page auto-redirect in the 404 pages too even it's not ideal from HTTP protocol pov.

**Comment by jmertic** [comment]
Good suggestion - I think two things might be good here.

1) Can you list the old site URIs that no longer work so I can put in redirects to the new locations?
2) Let's add a 404 to capture anything else that redirects to the main page.

Thoughts?

**Comment by jackjia-ibm** [comment]
That sounds great. Here are links we hosted before migration:

```
/home/
/download/
/about-us/
/contribute/
/faq/
```

There is one link `/code-guidelines/` we had removed from old website and content had been moved to docs-site.

**Comment by jmertic** [comment]
Fixed now - https://github.com/zowe/zowe.github.io/commit/f794dea637c0ed8e04a942d04a03bdf223bb4631
