### ISSUE TITLE
Add floating menu button or goto top button.

### ISSUE THREAD

**Issue by fbeyl** [zowe/zowe.github.io#44]
Pull down menu items cover content when pulled down and menu remains down after select. To go back to menu one has to go all the way back up or use the browser "go backwards one page", would be nice to have the menu button remain on top of viewport when scrolling down or have a goto top button remain at bottom.

**Comment by fbeyl** [comment]
@jmertic @jackjia-ibm Now @alexcontini added jquery I can use it to add 'goto top' button. Are there guideliness for colors to use? Is black the way to go (similar to the menu button) ?

**Comment by jmertic** [comment]
@alexcontini Can you comment here?

**Comment by alexcontini** [comment]
@fbeyl looks great! 
the only other color I would think of to use is the dark grey of the header or another grey, as blue will blend in when you scroll past those sections. I think black looks perfect!

**Comment by jmertic** [comment]
Is this still active?

**Comment by fbeyl** [comment]
Had some issues with git (novice user ;) ), created pull request. Still 2 DCO errors.

**Comment by jmertic** [comment]
Hey - try these instructions...

https://github.com/zowe/zowe.github.io/pull/58/checks?check_run_id=252553438

Thank you,

John Mertic
Director of Program Management - Linux Foundation
ASWF, ODPi, and Open Mainframe Project
jmertic@linuxfoundation.org
+1 234-738-4571
Schedule time with me at https://calendly.com/jmertic

**Comment by fbeyl** [comment]
Should be ok now.

**Comment by jmertic** [comment]
Closed with https://github.com/zowe/zowe.github.io/pull/58
