### ISSUE TITLE
V2 questions aren't numerated correctly

### ISSUE THREAD

**Issue by DivergentEuropeans** [zowe/zowe.github.io#467]
From Slack:

Also on https://www.zowe.org/vnext#latest-announcements page, the questions aren't numerated correctly (1. xxx, 1.xxx, 1.xxx etc) small things I'm finding randomly but nbd :slightly_smiling_face:

**Comment by devyloper** [comment]
> From Slack:
> 
> Also on https://www.zowe.org/vnext#latest-announcements page, the questions aren't numerated correctly (1. xxx, 1.xxx, 1.xxx etc) small things I'm finding randomly but nbd 🙂

I have corrected the numbering in after forking the repo in my profile. Also do I need to correct that in vNext.md? I have corrected it in a .gitignore file named vNext.html 
I am new to opensource contribution and if this pull request gets accepted it is going to be my first contribution.

**Comment by balhar-jakub** [comment]
Fixed now.
