### ISSUE TITLE
Add website privacy policy and cookie collection notice

### ISSUE THREAD

**Issue by nannanli** [zowe/zowe.github.io#665]
As an example, https://www.linuxfoundation.org/legal/privacy-policy

**Comment by balhar-jakub** [comment]
@nannanli I am willing to do the implementation for the website. 
Do we have the text and some visual on how approximately it should look like?

**Comment by nannanli** [comment]
@balhar-jakub Hi Jakub, @samanthasusu is working on the text and visual for the privacy policy and the cookie notice. Here is an example cookie notice from IBM website which I think is what we want to pursue. I'll let Sam chime in with more details. : )
![thumbnail_image](https://user-images.githubusercontent.com/14340789/236194518-2af32e7d-6a6d-486a-a0c2-a27a84d4f678.png)

**Comment by samanthasusu** [comment]
@balhar-jakub Hi Jakub, sorry for the late reply due to vacation. I have dropped it through email and feel free to slack me if any change is needed.

**Comment by balhar-jakub** [comment]
@samanthasusu Do you have a visual I can use to implement the cookie policy? The Privacy policy is already published.

**Comment by samanthasusu** [comment]
Hi @balhar-jakub Sorry about the late reply because of the national holiday. I don't have the visual for this but I can create one. Will a simple mockup design work for you, like a .jpg format mockup? Please let me know if you have any requirements on this. Thank you!

**Comment by balhar-jakub** [comment]
@samanthasusu Simple mockup design is fine, I can work with that further afterwards.

**Comment by samanthasusu** [comment]
![Untitled](https://github.com/zowe/zowe.github.io/assets/95402892/f9c3df7a-a735-4840-97e3-f6f1fe4accf4)
Hi @balhar-jakub please check this file and see if this works for you. Thanks!

**Comment by balhar-jakub** [comment]
@samanthasusu That's good enough, I will update the webpage

**Comment by jmertic** [comment]
If it's easier - just add this code as high up as possible in the HTML and it will take care of things for you....

`<script src="https://cmp.osano.com/16A0DbT9yDNIaQkvZ/3b49aaa9-15ab-4d47-a8fb-96cc25b5543c/osano.js"></script>`

**Comment by balhar-jakub** [comment]
@samanthasusu I added the policy as John proposed in this PR - https://github.com/zowe/zowe.github.io/pull/867

**Comment by samanthasusu** [comment]
> @samanthasusu I added the policy as John proposed in this PR - #867

Great. Thank you!
