### ISSUE TITLE
V3: vNext page should contain `V2 -> V3` changes

### ISSUE THREAD

**Issue by zFernand0** [zowe/zowe.github.io#817]
As more Zowe components start developing towards their pre-release  for V3, we need to provide with a common location for them to contribute their breaking changes and major features for people to try.

Ideally, we will keep the contents in [`vnext`](https://www.zowe.org/vnext) in case someone needs to migrate from V1 to V3 😋

**Comment by balhar-jakub** [comment]
Yes, we need to do this change.

**Comment by balhar-jakub** [comment]
It was prepared, now we need to add the information.
