### ISSUE TITLE
Enable zowe.org to allow downloading Zowe plugins

### ISSUE THREAD

**Issue by nannanli** [zowe/zowe.github.io#82]
- As end-user, we want to download Zowe plugins from trusted zowe.org website.
- As end-user, we should be able to see a list of all available Zowe plugins on zowe.org and choose what we want to download.

Create a Zowe `marketplace` that allow users to download and install plugins with a similar experience.  For example, https://marketplace.visualstudio.com/vscode.

**Comment by nannanli** [comment]
@jmertic Hi John, I created the issue in this repo to track this requirement received. Wondering if this is already in the OMP plan. I know we already have a page for all the [Zowe conformant plugins](https://landscape.openmainframeproject.org/category=zowe-conformant&format=logo-mode&grouping=category). This requirement is to allow users to see all the plugins that they could download and use in Zowe. Could you advise how to best proceed with this? Thank you!

**Comment by Joe-Winchester** [comment]
@nannanli - as part of the current PI we're looking to work out the procedure by which plugins can be delivered in a marketplace style.  We are planning to start with two Zowe samples (that aren't in the current download) and then include the IMS Operations API that has the epic https://github.com/zowe/community/issues/477.  What's good about all 3 of these is that they are open source owned (i.e. in github.com/zowe) so we are wanting to get them in the build pipeline, get tests for them, and then have a conformance criteria by which these can be distributed that is fair and equal so others could apply to have their plugins distributed.  I hope this will be done early in the current PI (i.e. the new month or so) which will also include yourself and others in the design of how the end user experience downloading the plugins, finding their doc, finding how they are supported, ... can take place   

The next step after these three would then be for us to consider how non github.com/zowe z/OS plugins are distributed.  This requires a bit more design and validation with the community of comformant plugin vendors to make sure they're happy with the solution, as these are owned and built and tested by vendors.  We also want to probably work with other open source communities to see how they tackle this problem.

**Comment by nannanli** [comment]
Thank you Joe @Joe-Winchester for the clarification! This issue intends to cover the first part of work that you mentioned. Because there is already an issue for the work, I'll close this one. The Zowe marketplace page needs more collaborative work and seems the community repo will be the best place to raise the discussion.
