### ISSUE TITLE
Burger menu button visible on desktop screen

### ISSUE THREAD

**Issue by sidharthbh8** [zowe/zowe.github.io#831]
When you open the [zowe.org](https://www.zowe.org/) site on top right there is a burger menu available on desktop screens and does nothing on click, as it works only in mobile screen when screen width is smaller than _991px_.

<img width="960" alt="zowe unresponsive" src="https://github.com/zowe/zowe.github.io/assets/92387052/0660ad6b-afef-4f41-b317-d263e3754b8e">

**Comment by balhar-jakub** [comment]
Thanks for the fix.
