### ISSUE TITLE
Add link to medium.com/zowe blog from zowe.org

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe.github.io#84]
Provide a way that users visiting zowe.org can navigate to the site https://medium.com/zowe

**Comment by Joe-Winchester** [comment]
cc: @nannanli

**Comment by jmertic** [comment]
Added PR for this - https://github.com/zowe/zowe.github.io/pull/85

That all said - let's not merge until the new editorial committee is up and going and Mae/Chris indicate that the branding is all correct.

**Comment by nannanli** [comment]
@jmertic Hi John, I have two questions that need your advice. Thanks in advance! 
- For the editorial committee, does it mean that all future zowe.org changes must be reviewed by the committee before it's published? If so, can we add the process and some details to the README file so people know what to expect after a PR is submitted? 
- There are some feedback on zowe.org design. I can summarize the feedback and create an issue in this repo later. I'm wondering for such enhancements, are we going to have a designer who can help with the UX design/review?
