### ISSUE TITLE
New animated logo performance regression

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zowe.github.io#875]
The zowe.org logo update in https://github.com/zowe/zowe.github.io/pull/873 caused a performance regression, because it is the second biggest asset loaded, slowing the page load down on slow connections.

Slow connection performance is important. You may view zowe.org on a hotel or conference wifi that is unbearably slow. You do not want to make the experience worse for first-time viewers.

<img width="824" alt="image" src="https://github.com/zowe/zowe.github.io/assets/30730276/940744d8-4aba-48a0-b127-7b58f3549f5a">

You can simulate the performance in dev tools by selecting "3G", as I did.
You will notice that the animation doesn't even animate well, due to its slow load.

This can be solved by optimization.
There is no reason to use an unoptimized GIF.
A simple fix is to convert it to APNG, a format supported by all browsers which is much more efficient. Example:
![ezgif com-gif-to-apng](https://github.com/zowe/zowe.github.io/assets/30730276/18ddeed3-c704-43c1-ba5f-0c84cb0e6c06)

This could be mitigated by https://github.com/zowe/zowe.github.io/pull/874

**Comment by 1000TurquoisePogs** [comment]
note: to a lesser extent, medium.com gifs are also large so people should avoid them too, but they only show up when scrolling further down the page.

**Comment by balhar-jakub** [comment]
The medium.com needs to be done differently. I intend to get to it at some point, but otherwise closing as the PR is merged.
