### ISSUE TITLE
Feedback on Zowe.org download redesign

### ISSUE THREAD

**Issue by nannanli** [zowe/zowe.github.io#96]
## Please leave your feedback as a comment on this issue.

The Zowe.org Download section has been redesigned for better usability. Download is now a standalone page which aims to help you better understand the meaning and relationship of the buttons and more easily find useful information such as release timeline. Check out the new design: https://deploy-preview-93--condescending-dubinsky-4645a9.netlify.app/download.html

As a community, we want to hear from you to make this better. Appreciate your time and comments.

**Comment by zFernand0** [comment]
I think this is a great improvement as to what we have today since it allows for a more streamlined way when it comes to adding new components to the Zowe ecosystems 👍

**Comment by RASakach** [comment]
I agree, great improvement!  Excellent work.  Thank you for taking on this effort!

Some comments and suggestions:

1. Include a boxed section at the very top that describes how the page is partitioned (e.g. _Zowe has both SERVER and CLIENT components, the title bar in the tiles below, indicates the applicable components.  Download the latest installer to install Zowe on the z/OS server, on your computer, or both. Start your journey with Zowe today!_)

2. Add a background color and bold the titles in each of the installer boxes (maybe a light gray?) to call them out

3. When referencing the different types of installs, use the same font/boldness that is used in the heading (e.g. Install Zowe z/OS components from the **Convenience build** or the **SMP/E build** depending on your need. Same with the Zowe CLI and Zowe Explorer

4. In the Previous Releases section, add another boxed section beneath the PREVIOUS RELEASES title that describes the installation / packaging prior to the 1.9 release (e.g. Note:  Zowe Release 1.0 - 1.8 were all-inclusive etc. etc. and require full installation, Release 1.9 (LTS) begins SMP/E Installation etc.)

**Comment by nannanli** [comment]
@RASakach Thank you Rose! Great suggestions. Will make the updates.
